version: "3"
services:
  api:
    build: "./api"
    ports:
      - "5000:5000"
    links: 
      - db
  db:
    build: "./db"
    ports:
      - "27017:27017"

  filebeat:
    hostname: filebeat
    image: filebeat:6.5.2
    build:
      context: docker-logs/filebeat
      dockerfile: Dockerfile
    volumes:
      # needed to access all docker logs (read only) :
     - "/var/lib/docker/containers:/usr/share/dockerlogs/data:ro"
      # needed to access additional informations about containers
     - "/var/run/docker.sock:/var/run/docker.sock"
    links:
       - elasticsearch
    depends_on: 
       - elasticsearch
  kibana:
    image: kibana:6.5.2
    environment:
      - "LOGGING_QUIET=true"
    links:
      - elasticsearch
    ports:
      - 5601:5601

  elasticsearch:
    hostname: elasticsearch
    image: elasticsearch:6.5.2
    build:
      context: docker-logs/elasticsearch
      dockerfile: Dockerfile
    environment:
      - cluster.name=docker-elk-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
  metricbeat:
    build: 
      context: monitoring/metricbeat
      dockerfile: Dockerfile
    environment:
      - "WAIT_FOR_HOSTS=elasticsearch:9200 kibana:5601"
      - "HOST_ELASTICSEARCH=elasticsearch:9200"
      - "HOST_KIBANA=kibana:5601"
    depends_on:
      - elasticsearch