version: 2
jobs:
  build:
    docker:
    - image: circleci/python:3.6.9
    steps:
    - checkout
    - run:
        command: docker-compose build
workflows:
  deploy:
    jobs:
    - build
  version: 2

# Original config.yml file:
# version: 2.1
# jobs:
#   build:
#     docker:
#       - image: circleci/python:3.6.9
#     steps:
#       - checkout
#       - run: docker-compose build
# 
# workflows:
#   deploy:
#     jobs:
#       - build