version: 2


jobs:
  deploy:
    docker:
      steps:
         - run: ssh -v $DROPLET_USER@$DROPLET_IP "cd /opt/thecatapi-lab && docker-compose build && docker-compose up -d"

workflows:
  main:
    jobs:
      - deploy
