version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6.9
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
              - "1b:49:ae:52:03:d6:99:ad:a6:37:e4:e1:cd:fc:d0:e6"
      - run: ssh -o StrictHostKeyChecking=no root@206.81.10.131 "cd /opt/thecatapi-lab/ %% docker-compose build"
      - run: ssh -o StrictHostKeyChecking=no root@206.81.10.131 "cd /opt/thecatapi-lab/ %% docker-compose up -d"
                  

workflows:
  deploy:
    jobs:
      - build
