version: 2.1


jobs:
  deploy:
    steps:
      - commands:
        - echo "deploying"
        - ssh -v $DROPLET_USER@$DROPLET_IP "cd /opt/thecatapi-lab && docker-compose build && docker-compose up -d"

workflows:
  main:
    jobs:
      - deploy
