version: 2.1
orbs:
  jira: circleci/jira@volatile
jobs:
  deploy:
    docker:
      - image: circleci/node:carbon
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
             - 24:2d:2c:b0:ed:e6:62:71:69:1a:ab:fb:5f:43:c6:dd
      - run:
         command: |
             echo Deploy
             echo $DROPLET_USER
             ssh -o "StrictHostKeyChecking=no" $DROPLET_USER@$DROPLET_IP "cd /opt/thecatapi-lab && docker-compose build && docker-compose up -d"

workflows:
  deploy:
    jobs:
      - deploy
