version: 2.1
jobs:
  deploy:
    docker:
      - image: circleci/python:3.6.9
    steps:
      - checkout
      
      - run:
         command: |
             echo Deploy
             ssh -o StrictHostKeyChecking=no root@206.81.10.131 "ls -l"
             #ssh  $DROPLET_USER@$DROPLET_IP "cd /opt/thecatapi-lab && docker-compose build && docker-compose up -d"

workflows:
  deploy:
    jobs:
      - deploy
