version: 2.1
orbs:
  jira: circleci/jira@volatile
jobs:
  deploy:
    docker:
      - image: circleci/node:carbon
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
             - 1b:49:ae:52:03:d6:99:ad:a6:37:e4:e1:cd:fc:d0:e6
      - run:
         command: |
             echo Deploy
             echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
             ssh -v $DROPLET_USER@$DROPLET_IP "cd /opt/thecatapi-lab && docker-compose build && docker-compose up -d"

workflows:
  deploy:
    jobs:
      - deploy
