global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  external_labels:
      monitor: 'prometheus-monitor'

scrape_configs:
- job_name: prometheus
  static_configs:
  - targets: ['prometheus:9090']

- job_name: api-thecats
  scrape_interval: 5s
  static_configs:
  - targets: ['api:5000']

- job_name: api-thecats-collector
  scrape_interval: 5s
  static_configs:
  - targets: ['collector:8000']

